### ISSUE TITLE
Neon Dash Add Visualization Error

### ISSUE THREAD

**Issue by saulgill** [NextCenturyCorporation/neon-dash-legacy#2] opened 2018-01-26 10:32 UTC
When adding a new bar-chart to the earthquakes data dashboard, after the bar-chart is inserted, the "Add Visualizations" window will not close when the "close button" is clicked. I am using Google Chrome version 64.0.3282.119 (Official Build) (64-bit). The following error is reported in the browser error console:

```
ERROR TypeError: Cannot read property 'ctx' of undefined
    at BarChartComponent.webpackJsonp.../../../../../src/app/components/bar-chart/bar-chart.component.ts.BarChartComponent.handleChangeChartType (bar-chart.component.ts:604)
    at BarChartComponent.webpackJsonp.../../../../../src/app/components/bar-chart/bar-chart.component.ts.BarChartComponent.postInit (bar-chart.component.ts:275)
    at BarChartComponent.webpackJsonp.../../../../../src/app/components/base-neon-component/base-neon.component.ts.BaseNeonComponent.ngOnInit (base-neon.component.ts:144)
    at checkAndUpdateDirectiveInline (core.es5.js:10843)
    at checkAndUpdateNodeInline (core.es5.js:12341)
    at checkAndUpdateNode (core.es5.js:12284)
    at debugCheckAndUpdateNode (core.es5.js:13141)
    at debugCheckDirectivesFn (core.es5.js:13082)
    at Object.eval [as updateDirectives] (BarChartComponent_Host.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13067)
```
This error is new. I only experienced it yesterday. I have been using neon dash for about a week and have not seen it before.

Thanks

**Comment by Konnoke** [comment] 2018-01-31 18:42
This is caused by https://github.com/NextCenturyCorporation/neon-dash/commit/a782223050c71982deb12279d4b1bb04575356b8 when we added the radio button to change the chart type between horizontal and vertical.

Thanks for letting us know. We'll try to fix this for our next sprint!

**Comment by Konnoke** [comment] 2018-02-08 20:17
This is now fixed in the angular 5 branch.

**Closed as completed** 2018-04-11 01:33 UTC
